name: Bri
favicon: null
layout_spectrum: 0.99706
typography_spectrum: 0.228777757845819
title: You and I
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#183a5f'
    - '#3a8ac9'
    - '#826f4e'
    - '#aeafaa'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.1959359748288989
  rhythmicContrast: 0.5
purpose: []
